### ISSUE TITLE
Don't work with autoload

### ISSUE THREAD

**Issue by viandanteoscuro** [samayo/Autolog#2]
Hi,

When i instantiate the class, i have the following error:

PHP Warning:  require(/var/www/html/api/movimentazione/vendor/composer/../samayo/autolog/src/autolog.php): failed to open stream: No such file or directory

How can i resolve this problem?

Thanks

**Comment by samayo** [comment]
Hi, I'm very sorry for giving you this irritating issue, I hope you didn't waste too much time on it. I see there is some composer issue, and I forgot to rename the autoload. In short, for now you can require manually the autolog.php class and instantiate the object as `new \Autolog\Logger` until I find the issue

**Comment by samayo** [comment]
fixed, sorry for this
